site_name: OpenINS Documentation
docs_dir: docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: red
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'Home': 'index.md'
  - 'Contributing': 'CONTRIBUTING.md'
  - 'Getting Started': 'getting_started.md'
  - 'RF Basics': 'rf_basics.md'
  - 'Sensor Fusion Basics': 'sensor_fusion.md'
  - 'Algorithms': 'algorithms.md'
  - 'Design Choices': 'design_choices.md'

plugins:
  - search
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences